export const processTaskCompletion = (store, task, myName) => {
    const now = new Date();
    const localTodayStr = new Date(now.getTime() - (now.getTimezoneOffset() * 60000)).toISOString().split('T')[0];
    const nowTime = now.getTime();

    let sessionTime = 0;
    if (task.startedAt && task.executingStatus === 'playing') {
        sessionTime = nowTime - new Date(task.startedAt).getTime();
    }
    const totalAccumulated = (task.accumulatedTimeMs || 0) + sessionTime;

    let xpGanho = 25;
    if (task.peso === 'media') xpGanho = 50;
    if (task.peso === 'alta') xpGanho = 100;

    if (store && store.client) {
        xpGanho = Math.round(xpGanho * 1.5);
    }

    let updatedChecklists = store.checklists.map(c => 
        c.id === task.id ? { 
            ...c, 
            feita: true,
            completedAt: localTodayStr,
            completedAtFull: now.toISOString(),
            completedBy: myName,
            executingStatus: 'completed',
            accumulatedTimeMs: totalAccumulated
        } : c
    );

    if (task.recorrencia && task.recorrencia !== 'none' && task.recorrencia !== 'ghost' && task.data) {
        const [year, month, day] = task.data.split('-').map(Number);
        let nextDateObj = new Date(year, month - 1, day);
        
        if (task.recorrencia === 'daily') nextDateObj.setDate(nextDateObj.getDate() + 1);
        if (task.recorrencia === 'weekly') nextDateObj.setDate(nextDateObj.getDate() + 7);
        
        if (task.recorrencia === '3days') nextDateObj.setDate(nextDateObj.getDate() + 3); // Oferta Relâmpago TikTok
        if (task.recorrencia === '15days') nextDateObj.setDate(nextDateObj.getDate() + 15); // Quinzenal
        if (task.recorrencia === 'monthly') nextDateObj.setMonth(nextDateObj.getMonth() + 1); // Mensal (30 dias)
        if (task.recorrencia === '90days') nextDateObj.setDate(nextDateObj.getDate() + 90); // Promoção Padrão / Trimestre

        const nextDateStr = `${nextDateObj.getFullYear()}-${String(nextDateObj.getMonth() + 1).padStart(2, '0')}-${String(nextDateObj.getDate()).padStart(2, '0')}`;
        
        updatedChecklists.push({
            ...task,
            id: Date.now() + Math.random(),
            data: nextDateStr,
            feita: false,
            executingStatus: 'none',
            accumulatedTimeMs: 0,
            startedAt: null,
            startedBy: null,
            completedAt: null,
            completedAtFull: null,
            completedBy: null,
            isAutoGenerated: true
        });
    }

    let logTexto = `✅ Tarefa concluída: "${task.texto}" (+${xpGanho} XP)`;
    if (task.criadoPor && task.criadoPor !== myName) {
        logTexto = `✅ @${task.criadoPor}, a tarefa "${task.texto}" foi concluída! (+${xpGanho} XP)`;
    }

    const newLog = {
        id: Date.now() + Math.random(),
        data: now.toLocaleString('pt-BR'),
        texto: logTexto,
        author: myName
    };

    return { updatedChecklists, newLog, xpGanho };
};

export const processTaskStart = (store, task, myName) => {
    const now = new Date();
    
    const updatedChecklists = store.checklists.map(c => 
        c.id === task.id ? { 
            ...c, 
            startedAt: c.startedAt || now.toISOString(), // Mantém o início original se for uma retomada
            executingStatus: 'playing', 
            startedBy: myName,
            responsavel: myName // Garante que quem iniciou é o dono no roteiro
        } : c
    );

    const newLog = { 
        id: Date.now() + Math.random(), 
        data: now.toLocaleString('pt-BR'), 
        texto: `▶️ Iniciou a execução da tarefa: "${task.texto}"`, 
        author: myName 
    };

    return { updatedChecklists, newLog };
};

export const processTaskPause = (store, task, myName) => {
    const nowTime = new Date().getTime();
    
    const updatedChecklists = store.checklists.map(c => {
        if (c.id === task.id) {
            const sessionTime = c.startedAt ? nowTime - new Date(c.startedAt).getTime() : 0;
            return { 
                ...c, 
                executingStatus: 'paused', 
                accumulatedTimeMs: (c.accumulatedTimeMs || 0) + sessionTime, 
                startedAt: null 
            };
        }
        return c;
    });

    const newLog = { 
        id: Date.now() + Math.random(), 
        data: new Date().toLocaleString('pt-BR'), 
        texto: `⏸️ Pausou a tarefa: "${task.texto}"`, 
        author: myName 
    };

    return { updatedChecklists, newLog };
};

export const calculateNextAccess = (checklists) => {
    if (!checklists || checklists.length === 0) return '';
    
    const pendingWithDate = checklists.filter(t => !t.feita && t.data);
    
    if (pendingWithDate.length > 0) {
        pendingWithDate.sort((a, b) => {
            const dateA = new Date(`${a.data}T${a.hora || '00:00'}:00`);
            const dateB = new Date(`${b.data}T${b.hora || '00:00'}:00`);
            return dateA - dateB;
        });
        return `${pendingWithDate[0].data}T${pendingWithDate[0].hora || '00:00'}`;
    }
    
    return ''; 
};

export const processTaskSchedule = (store, task, myName) => {
    const now = new Date();
    
    const updatedChecklists = store.checklists.map(c => 
        c.id === task.id ? { 
            ...c, 
            executingStatus: 'scheduled', // Muda o status para programada
            responsavel: myName // O usuário que puxou assume a responsabilidade
        } : c
    );

    const newLog = { 
        id: Date.now() + Math.random(), 
        data: now.toLocaleString('pt-BR'), 
        texto: `📅 Puxou a tarefa para o Roteiro Diário: "${task.texto}"`, 
        author: myName 
    };

    return { updatedChecklists, newLog };
};
